set the task result

diff --git a/.azure-pipelines/templates/go/GenerateCode.yml b/.azure-pipelines/templates/go/GenerateCode.yml
--- a/.azure-pipelines/templates/go/GenerateCode.yml
+++ b/.azure-pipelines/templates/go/GenerateCode.yml
@@ -13,6 +13,7 @@ steps:
     
     if [ "$?" != "0" ]; then
       echo "failed to generate readme config file"
+      echo "##vso[task.setvariable variable=Task_Result]failure"
     else
       echo "readme config file generated"
       cd $(Pipeline.Workspace)/s/azure-rest-api-specs
@@ -52,6 +53,13 @@ steps:
     outputfolder="$gosdkfolder/$moduleName"
     cd $(Pipeline.Workspace)/s
     autorest --version=3.2.1 --use=https://amecodegenstorage.blob.core.windows.net/tools/autorest-tests-0.0.1.tgz $(Pipeline.Workspace)/s/azure-rest-api-specs/specification/$(ResourceProvider)/resource-manager/readme.md --use=@autorest/go@4.0.0-preview.22 --file-prefix="zz_generated_" --track2 --go --output-folder=$outputfolder 1>>$(TASK_KEY).log 2>&1
+    if [ "$?" != "0" ]; then
+      echo -e "\e[31m[$(date -u)] ERROR: [$OPERATION : $(ResourceProvider)]: Generate go sdk failed"
+      az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
+      az storage blob upload -c depthcoverage -f $(TASK_KEY).log -n log/$(CodeGenerationName)-$(Build.BuildId)-$(TASK_KEY).log --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=depthcoverage
+      echo "##vso[task.setvariable variable=Task_Result]failure"
+      exit 1
+    fi
   displayName: 'Generate Mock Test case'
 - bash: |
     cd $(Pipeline.Workspace)/s/azure-sdk-for-go
diff --git a/.azure-pipelines/templates/go/RunMockTest.yml b/.azure-pipelines/templates/go/RunMockTest.yml
--- a/.azure-pipelines/templates/go/RunMockTest.yml
+++ b/.azure-pipelines/templates/go/RunMockTest.yml
@@ -12,4 +12,11 @@ steps:
     ls -l $(Pipeline.Workspace)/s/go/bin
     go mod tidy
     $(Pipeline.Workspace)/s/go/bin/gotestsum --format testname -- -coverprofile cover.out
+    if [ "$?" != "0" ]; then
+      echo -e "\e[31m[$(date -u)] ERROR: [$(ResourceProvider)]: Go Mock Test failed"
+      az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
+      az storage blob upload -c depthcoverage -f $(TASK_KEY).log -n log/$(CodeGenerationName)-$(Build.BuildId)-$(TASK_KEY).log --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=depthcoverage
+      echo "##vso[task.setvariable variable=Task_Result]failure"
+      exit 1
+    fi
   displayName: 'Mock Test'
