setup TF test env

diff --git a/.azure-pipelines/templates/RunTFMockTest.yml b/.azure-pipelines/templates/RunTFMockTest.yml
--- a/.azure-pipelines/templates/RunTFMockTest.yml
+++ b/.azure-pipelines/templates/RunTFMockTest.yml
@@ -1,4 +1,29 @@
 steps:
-- script: |
-    make acctests SERVICE=${ResourceProvider} TESTARGS=-run=TestAcc[a-zA-Z]+_mockserver[a-zA-Z0-9]+ TESTTIMEOUT='60m' 1>$(TASK_KEY).log 2>&1
+- bash: |
+    echo "$(srcPackage)"
+    echo "$(prefix)"
+    DIR=./go/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/$(ResourceProvider)$(prefix)
+    pwd
+    echo "$DIR"
+    if [ -d "$DIR" ]; then
+      echo "$DIR exists."
+      echo "##vso[task.setvariable variable=srcPackage]$(ResourceProvider)$(prefix)"
+      echo "$(srcPackage)"
+      echo "$(prefix)"
+    else
+      echo "$DIR does not exists."
+      echo "##vso[task.setvariable variable=srcPackage]$(ResourceProvider)"
+    fi
+  displayName: "source package"
+- bash: |
+    set -x
+    cd ./go/src/github.com/terraform-providers/terraform-provider-azurerm
+    pwd
+    make acctests SERVICE=$(srcPackage) TESTARGS=-run=TestAcc[a-zA-Z]+_mockserver[a-zA-Z0-9]+ TESTTIMEOUT='60m' 1>$(TASK_KEY).log 2>&1
+    if [ "$?" != "0" ]; then
+      echo -e "\e[31m[$(date -u)] ERROR: [$(ResourceProvider)]: TF Mock Test failed"
+      az login --service-principal -u $(SERVICE_PRINCIPE_ID) -p $(SERVICE_PRINCIPE_SECRET) --tenant $(SERVICE_PRINCIPE_TENANT)
+      az storage blob upload -c depthcoverage -f $(TASK_KEY).log -n log/$(TARGET)-$(ResourceProvider)-$(Build.BuildId)-$(TASK_KEY).log --subscription $(SERVICE_PRINCIPE_SUBSCRIPTION) --account-name=depthcoverage
+      exit 1
+    fi
   displayName: 'MockTest TF'
